import {randomBytes,randomInt,randomUUID,scryptSync,timingSafeEqual} from 'node:crypto';
export function createEmailAuth({sql,transact,load,hash,rate,fail,phone,text,status,accountFor,audit,mailer}){
  sql.exec('CREATE TABLE IF NOT EXISTS email_credentials(email TEXT PRIMARY KEY,password TEXT NOT NULL,principal TEXT NOT NULL,verified INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS email_challenges(id TEXT PRIMARY KEY,email TEXT NOT NULL,code TEXT NOT NULL,purpose TEXT NOT NULL,payload TEXT NOT NULL,expires INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0);');
  const admin=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase();
  sql.exec('CREATE TABLE IF NOT EXISTS staff_credentials(username TEXT PRIMARY KEY,password TEXT NOT NULL,principal TEXT NOT NULL);');
  const username=v=>{const u=String(v||'').trim().toLowerCase();if(!/^[a-z0-9._-]{3,32}$/.test(u))fail('اسم المستخدم من 3 إلى 32 حرفًا إنجليزيًا أو رقمًا، ويقبل النقطة والشرطة.');return u;};
  function pin(v){if(!/^\d{6}$/.test(String(v||'')))fail('كلمة مرور الموظف 6 أرقام.');const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(String(v),salt,64).toString('hex');}
  function provisionStaff(p,u,v){u=username(u);if(sql.prepare('SELECT username FROM staff_credentials WHERE username=?').get(u))fail('اسم المستخدم مستخدم بالفعل.');sql.prepare('INSERT INTO staff_credentials VALUES(?,?,?)').run(u,pin(v),JSON.stringify(p));return u;}
  function resetStaff(employee,v){const stored=pin(v),rows=sql.prepare('SELECT username,principal FROM staff_credentials').all(),row=rows.find(r=>JSON.parse(r.principal).employee===employee);if(!row)fail('الموظف لا يملك اسم مستخدم.',404);sql.prepare('UPDATE staff_credentials SET password=? WHERE username=?').run(stored,row.username);for(const s of sql.prepare('SELECT hash,principal FROM sessions').all())if(JSON.parse(s.principal).employee===employee)sql.prepare('DELETE FROM sessions WHERE hash=?').run(s.hash);}
  function staffLogin(b,ip){const u=String(b.username||'').trim().toLowerCase();rate('staff-ip:'+ip,20,600000);rate('staff-login:'+hash(u),5,600000);const c=sql.prepare('SELECT * FROM staff_credentials WHERE username=?').get(u);if(!c||!/^\d{6}$/.test(String(b.password||''))||!matches(String(b.password),c.password)){if(!c)scryptSync('invalid-password','dummy-salt',64);fail('اسم المستخدم أو كلمة المرور غير صحيحة.',401);}const p=JSON.parse(c.principal),sh=load().shops.find(s=>s.id===p.shop);if(!sh?.employees.some(e=>e.id===p.employee&&e.status==='active'))fail('وصول الموظف موقوف.',403);return session(p);}
  const email=v=>{const e=String(v||'').trim().toLowerCase();if(e.length>254||! /^[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$/i.test(e))fail('أدخل بريدًا إلكترونيًا صحيحًا.');return e;};
  function password(v){if(typeof v!=='string'||v.length<10||v.length>128)fail('كلمة المرور من 10 إلى 128 حرفًا.');const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(v,salt,64).toString('hex');}
  function matches(v,stored){if(typeof v!=='string'||v.length>128)return false;const [salt,digest]=stored.split(':'),a=scryptSync(v,salt,64),b=Buffer.from(digest,'hex');return a.length===b.length&&timingSafeEqual(a,b);}
  const credential=e=>sql.prepare('SELECT * FROM email_credentials WHERE email=?').get(e);
  function employeeByEmail(e){return load().shops.flatMap(sh=>sh.employees.filter(x=>x.email===e&&x.status==='active').map(x=>({kind:'employee',shop:sh.id,employee:x.id,phone:x.phone,email:e})))[0];}
  async function challenge(e,purpose,payload={}){rate('email-send:'+hash(e),3,600000);if(!mailer.ready())fail('خدمة البريد قيد الإعداد. حاول لاحقًا.',503);const id=randomUUID(),code=mailer.provider==='test'?'123456':String(randomInt(100000,1000000));sql.prepare('DELETE FROM email_challenges WHERE email=? AND purpose=?').run(e,purpose);sql.prepare('INSERT INTO email_challenges(id,email,code,purpose,payload,expires) VALUES(?,?,?,?,?,?)').run(id,e,hash(id+':'+code),purpose,JSON.stringify(payload),Date.now()+600000);try{await mailer.send(e,code,purpose);}catch(err){sql.prepare('DELETE FROM email_challenges WHERE id=?').run(id);throw err;}return {challenge:id,step:'otp',...(mailer.provider==='test'?{testCode:code}:{})};}
  function session(principal){const token=randomBytes(32).toString('hex');sql.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),JSON.stringify(principal),Date.now()+12*3600000);return {principal,token};}
  async function request(b,ip){const e=email(b.email);rate('email-login:'+hash(e),10,600000);rate('email-ip:'+ip,30,600000);const kind=b.kind;if(kind==='admin'){if(e!==admin)fail('هذا البريد غير مخول للإدارة.',403);return challenge(e,'admin');}if(!['owner','employee'].includes(kind))fail('نوع دخول غير صحيح.');const c=credential(e);if(b.reset){if(c&&JSON.parse(c.principal).kind===kind)return challenge(e,'reset',{kind});if(kind==='employee'){const p=employeeByEmail(e);if(p)return challenge(e,'invite',{principal:p});}return {step:'sent',message:'إذا كان البريد مسجلًا، ستصلك رسالة لاستعادة الحساب.'};}if(b.register){if(kind!=='owner'||e===admin||c||load().accounts.some(a=>a.email===e))fail('تعذر إنشاء الحساب بهذا البريد.');const p=phone(b.phone),name=text(b.name,40),business=text(b.business,36);if(!name||!business)fail('أدخل الاسم واسم النشاط.');if(load().accounts.some(a=>a.phone===p))fail('رقم الجوال مسجل بالفعل.');return challenge(e,'register',{name,business,phone:p,password:password(b.password)});}if(!c||JSON.parse(c.principal).kind!==kind){scryptSync('invalid-password','dummy-salt',64);fail('البريد أو كلمة المرور غير صحيحة.',401);}if(!matches(b.password,c.password))fail('البريد أو كلمة المرور غير صحيحة.',401);const p=JSON.parse(c.principal);if(p.kind==='employee'&&!employeeByEmail(e))fail('وصول الموظف موقوف.',403);if(!c.verified)return challenge(e,'verify',{kind});return session(p);}
  function verify(b,ip){rate('email-verify-ip:'+ip,30,600000);const c=sql.prepare('SELECT * FROM email_challenges WHERE id=?').get(text(b.challenge,70));if(!c||c.expires<Date.now()||c.attempts>=5)fail('رمز التحقق منتهٍ أو غير صالح.');sql.prepare('UPDATE email_challenges SET attempts=attempts+1 WHERE id=?').run(c.id);if(!/^\d{6}$/.test(String(b.code||''))||hash(c.id+':'+b.code)!==c.code)fail('رمز التحقق غير صحيح.');const payload=JSON.parse(c.payload);let principal;sql.exec('BEGIN IMMEDIATE');try{if(!sql.prepare('DELETE FROM email_challenges WHERE id=?').run(c.id).changes)fail('استخدم الرمز بالفعل.');if(c.purpose==='admin'){if(c.email!==admin)fail('غير مسموح.',403);principal={kind:'admin',phone:process.env.ADMIN_PHONES?.split(',')[0]||'',email:c.email};}else if(c.purpose==='register'){if(credential(c.email))fail('الحساب مسجل بالفعل.');const s=load();if(s.accounts.some(a=>a.email===c.email||a.phone===payload.phone))fail('الحساب مسجل بالفعل.');const id=randomUUID(),a={id:'USER-'+randomUUID().slice(0,8).toUpperCase(),name:payload.name,phone:payload.phone,email:c.email,shop:id,created:Date.now(),subscription:{status:'pending',expires:null,period:null,plan:'basic'}};s.accounts.push(a);s.shops.push({id,name:payload.business,status:'active',branch:'الفرع الرئيسي',card:{name:payload.business,category:'كافيه',icon:'coffee',color:'#204b3c',accent:'#d6ff76',target:4,reward:'قهوة مجانية',pattern:true,terms:'ختم لكل زيارة مؤهلة ومدفوعة.',logo:''},members:[],employees:[],logs:[]});audit(s,c.email,'تسجيل حساب جديد',a);sql.prepare('UPDATE state SET json=? WHERE id=1').run(JSON.stringify(s));principal={kind:'owner',account:a.id,shop:id,phone:a.phone,email:c.email};sql.prepare('INSERT INTO email_credentials VALUES(?,?,?,1)').run(c.email,payload.password,JSON.stringify(principal));}else if(c.purpose==='invite'){principal=employeeByEmail(c.email);if(!principal)fail('الدعوة غير متاحة.',403);sql.prepare('INSERT OR REPLACE INTO email_credentials VALUES(?,?,?,1)').run(c.email,password(b.password),JSON.stringify(principal));}else{const user=credential(c.email);if(!user)fail('الحساب غير موجود.',404);principal=JSON.parse(user.principal);if(c.purpose==='reset'){sql.prepare('UPDATE email_credentials SET password=?,verified=1 WHERE email=?').run(password(b.password),c.email);const sessions=sql.prepare('SELECT hash,principal FROM sessions').all();for(const s of sessions)if(JSON.parse(s.principal).email===c.email)sql.prepare('DELETE FROM sessions WHERE hash=?').run(s.hash);}else sql.prepare('UPDATE email_credentials SET verified=1 WHERE email=?').run(c.email);}sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}return session(principal);}
  function enroll(b,ip){rate('enroll-ip:'+ip,10,600000);const p=phone(b.phone),name=text(b.name,40);if(!name)fail('أدخل اسم العميل.');const principal=transact(s=>{const sh=s.shops.find(x=>x.id===b.shop);if(!sh||sh.archivedAt||status(accountFor(s,sh))!=='active'||sh.status!=='active')fail('التسجيل غير متاح.',403);if(sh.members.some(m=>m.phone===p))fail('الرقم مسجل في البرنامج. اطلب من الموظف مساعدتك في استرجاع البطاقة.',409);const m={id:'RJ-'+randomUUID().slice(0,12).toUpperCase(),name,phone:p,stamps:0,rewards:0,visits:0,joined:Date.now()};sh.members.push(m);return {kind:'customer',shop:sh.id,member:m.id,phone:p};});return session(principal);}
  return {request,verify,enroll,email,provisionStaff,resetStaff,staffLogin};
}
