import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {validateSettings,prepareDrafts,createEngagement} from './engagement.mjs';
const require=createRequire(import.meta.url),E=require('./dist/engagement.js'),L=require('./dist/loyalty.js');
const sh={id:'a',card:{target:4,reward:'coffee',program:{type:'points',pointsPerVisit:10,pointsCost:100}},members:[],logs:[]},m={id:'m',points:0,stamps:0,visits:5,rewards:0};sh.members.push(m);
const config=E.defaults();config.levels.enabled=true;config.levels.tiers[0].multiplier=2;config.offers=[{name:'quiet',enabled:true,days:[5],start:'22:00',end:'02:00',from:'2026-10-09',until:'2026-10-09',branchIds:['branch'],multiplier:3}];
sh.engagement=validateSettings(config,sh,[{id:'branch',status:'active'}]);
const time=Date.parse('2026-10-09T20:00:00Z'); // Friday 23:00 Riyadh.
assert.equal(E.award(sh,m,'branch',time).points,30);assert.equal(E.award(sh,m,'foreign',time).points,20);
assert.equal(E.award(sh,m,'branch',Date.parse('2026-10-09T22:59:59Z')).points,30); // Saturday 01:59.
assert.equal(E.award(sh,m,'branch',Date.parse('2026-10-09T23:00:00Z')).points,20); // Exclusive end.
assert.equal(E.award(sh,m,'branch',Date.parse('2026-10-10T20:00:00Z')).points,20);
assert.equal(E.award(sh,m,'branch',Date.parse('2026-10-09T18:59:59Z')).points,20);
const original=L.snapshot(m,sh.card),res=L.apply(m,sh.card,'stamp',{pointsAward:E.award(sh,m,'branch',time).points});assert.equal(m.points,30);assert.equal(m.visits,6);Object.assign(m,res.before);assert.deepEqual(L.snapshot(m,sh.card),original);
const legacy={...sh,engagement:undefined};assert.equal(E.award(legacy,m,'branch',time).points,10);assert.equal(E.level(legacy,m,time),null);
const old={member:'m',type:'stamp',time:time-100*E.DAY,saleAmount:100},recent={member:'m',type:'stamp',time:time-10*E.DAY,saleAmount:75},undone={member:'m',type:'stamp',time:time-5*E.DAY,saleAmount:1000,undone:true};sh.logs=[old,recent,undone];
sh.engagement.levels.metric='spend';sh.engagement.levels.window=90;assert.equal(E.level(sh,m,time).value,75);sh.engagement.levels.metric='visits';assert.equal(E.level(sh,m,time).value,1);sh.engagement.levels.window=0;assert.equal(E.level(sh,m,time).value,5);
for(const mutate of [c=>c.levels.tiers[1].threshold=1,c=>c.offers[0].branchIds=['foreign'],c=>c.offers[0].start='25:00',c=>c.offers[0].until='2026-02-30',c=>c.reminders[0].template='Unsafe Template',c=>c.offers[0].enabled='true',c=>c.levels.tiers[0].multiplier=9]){const c=structuredClone(config);mutate(c);assert.throws(()=>validateSettings(c,sh,[{id:'branch',status:'active'}]));}
assert.throws(()=>validateSettings(config,{...sh,card:{...sh.card,program:{type:'visits'}}},[{id:'branch',status:'active'}]));
sh.engagement.reminders[0].enabled=true;sh.engagement.reminders[0].days=7;assert.equal(prepareDrafts(sh,time).created,1);assert.equal(prepareDrafts(sh,time+60000).created,0);assert.equal(sh.engagementDrafts[0].status,'draft');
sh.logs.push({member:'m',type:'stamp',time:time+100000});prepareDrafts(sh,time+100000);assert.equal(sh.engagementDrafts[0].status,'cancelled');assert.equal(prepareDrafts(sh,time+8*E.DAY).created,0);assert.equal(prepareDrafts(sh,time+31*E.DAY).created,1);
const big={...legacy,members:Array.from({length:1100},(_,n)=>({id:'m'+n,points:100,visits:1})),engagement:E.defaults()};big.engagement.reminders[2].enabled=true;assert.equal(prepareDrafts(big,time).created,1000);assert.equal(prepareDrafts(big,time+60000).created,0);assert.equal(big.engagementDrafts.length,1000);assert.equal(prepareDrafts(big,time+8*E.DAY).created,1000);assert.equal(prepareDrafts(big,time+8*E.DAY+60000).created,0);
// No sender or network credential is used by preparation, even in an active account.
let network=0;const originalFetch=globalThis.fetch;globalThis.fetch=()=>{network++;throw Error('Unexpected outbound send');};try{let state={shops:[big]};const module=createEngagement({load:()=>state,transact:fn=>fn(state),status:()=> 'active',accountFor:()=>({}),authorized:()=>big,fail:(v,s)=>{throw Object.assign(Error(v),{status:s});},enqueue:()=>{throw Error('Unexpected wallet queue');}});module.settle();assert.equal(network,0);}finally{globalThis.fetch=originalFetch;}
const expiry={id:'expiry',status:'active',card:sh.card,members:[{id:'x',visits:2}],logs:[{type:'stamp',member:'x',time:time-89*E.DAY}],engagement:{levels:{enabled:true,metric:'visits',window:90,tiers:[{id:'gold',name:'Gold',threshold:1,multiplier:1,benefit:''}]}}};let writes=0,queued=0;const state={shops:[expiry]},module=createEngagement({load:()=>state,transact:fn=>{writes++;return fn(state);},status:()=> 'active',accountFor:()=>({}),authorized:()=>expiry,fail:(v,s)=>{throw Object.assign(Error(v),{status:s});},enqueue:()=>queued++});module.settle(time);assert.equal(queued,1);module.settle(time+60000);assert.equal(queued,1);assert.equal(writes,1);module.settle(time+2*E.DAY);assert.equal(queued,2);module.settle(time+2*E.DAY+60000);assert.equal(queued,2);expiry.status='paused';expiry.members[0].engagementWalletLevel='stale';module.settle(time+3*E.DAY);assert.equal(queued,2);
console.log('PASS: tier thresholds and rolling windows, recorded spend, Riyadh midnight/date/branch boundaries, highest multiplier without stacking, unchanged default points, undo snapshot, validation, reminders deduplication/cancellation/capacity and no external sending; expired rolling tiers queue once, unchanged and paused accounts do not queue.');
