import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createGrowth,growthReport} from './growth.mjs';
const Loyalty=createRequire(import.meta.url)('./dist/loyalty.js');
const DAY=86400000,time=Date.now(),card={target:2,reward:'هدية قديمة',color:'#204b3c',accent:'#d6ff76',icon:'coffee',program:{type:'visits'},rewardChoices:[{id:'a',label:'قهوة'},{id:'b',label:'حلوى'}]};
const fresh={id:'friend',name:'صديق',phone:'0501111111',joined:time,stamps:0,points:0,rewards:0,visits:0};
const inviter={id:'inviter',name:'داعٍ',phone:'0502222222',joined:time-50*DAY,stamps:1,rewards:0,visits:1,referralToken:'opaque-token'};
let state={accounts:[{id:'owner',shop:'shop',subscription:{status:'active'}}],shops:[{id:'shop',name:'نشاط',status:'active',card:structuredClone(card),growth:{referralsEnabled:true,referralReward:'هدية دعوة'},members:[inviter,fresh],logs:[]}]};
const load=()=>state,fail=(m,status=400)=>{throw Object.assign(Error(m),{status});},transact=fn=>{const next=structuredClone(state),result=fn(next);state=next;return result;},updates=[];
const growth=createGrowth({load,transact,authorized:()=>{},status:a=>a.subscription.status,accountFor:s=>s.accounts[0],fail,origin:'https://rg3h.cc',enqueue:id=>updates.push(id)});
let sh=state.shops[0],m=sh.members[1];growth.attachReferral(sh,m,'opaque-token');
assert.throws(()=>growth.attachReferral(sh,{...m,phone:inviter.phone},'opaque-token'));
growth.onStamp(sh,m,{id:'zero',time,saleAmount:0});assert.equal(m.referral.status,'waiting');
growth.onStamp(sh,m,{id:'missing',time});assert.equal(m.referral.status,'waiting');
const paid={id:'paid',type:'stamp',member:m.id,time,saleAmount:25};sh.logs.push(paid);growth.onStamp(sh,m,paid);assert.equal(m.referral.status,'pending');
growth.settle(time+300000);assert.equal(state.shops[0].members[1].referral.status,'pending');
growth.onUndo(sh,m,paid);paid.undone=true;growth.settle(time+400000);assert.equal(state.shops[0].members[1].referral.status,'waiting');assert.equal(m.rewards,0);
const second={id:'second',type:'stamp',member:m.id,time:time+500000,saleAmount:25};sh.logs.push(second);growth.onStamp(sh,m,second);growth.settle(time+900000);
sh=state.shops[0];assert.equal(sh.members[1].referral.status,'awarded');assert.equal(sh.members[0].rewards,1);assert.equal(sh.members[1].rewards,1);
growth.settle(time+1000000);assert.equal(state.shops[0].members[0].rewards,1);assert.equal(updates.length,1);
const bonus=Loyalty.apply(state.shops[0].members[0],card,'redeem');assert.equal(bonus.reward.label,'هدية دعوة');
const concurrentMember={stamps:1,points:0,rewards:0,visits:1,rewardItems:[]};const beforeConcurrent=Loyalty.snapshot(concurrentMember,card);const independent={id:'REF-new-inviter',type:'referral',label:'هدية لاحقة',earnedAt:time+1};concurrentMember.rewardItems=[independent];concurrentMember.rewards=1;growth.restore(sh,concurrentMember,{time,before:beforeConcurrent});assert.deepEqual(concurrentMember.rewardItems,[independent]);assert.equal(concurrentMember.rewards,1);
const member={stamps:0,rewards:0,visits:0};Loyalty.apply(member,card,'stamp');Loyalty.apply(member,card,'stamp');assert.equal(Loyalty.nextChoices(member,card).length,2);assert.throws(()=>Loyalty.apply(member,card,'redeem'));assert.equal(member.rewards,1);
const changed={...card,rewardChoices:[{id:'new',label:'هدية مختلفة'}]};member.rewardChoiceId='b';const redeemed=Loyalty.apply(member,changed,'redeem');assert.equal(redeemed.reward.label,'حلوى');assert.equal(member.rewards,0);assert.equal(member.rewardChoiceId,undefined);Object.assign(member,redeemed.before);assert.equal(member.rewards,1);assert.equal(member.rewardChoiceId,'b');
const legacy={stamps:0,rewards:1,visits:2};assert.equal(Loyalty.apply(legacy,card,'redeem').reward.label,'هدية قديمة');
const points={points:100,rewards:0,visits:2};assert.throws(()=>Loyalty.apply(points,{...card,program:{type:'points'}},'redeem',{choiceId:'foreign'}));assert.equal(points.points,100);assert.equal(Loyalty.apply(points,{...card,program:{type:'points'}},'redeem',{choiceId:'a'}).reward.label,'قهوة');assert.equal(points.points,0);
const reportShop={...sh,card,members:[{id:'old',name:'قديم',joined:time-60*DAY,stamps:1},{id:'new',name:'جديد',joined:time-2*DAY},{id:'ready',name:'جاهز',joined:time-10*DAY,rewards:1}],logs:[{id:'x',type:'stamp',member:'old',time:time-40*DAY,branchId:'a',saleAmount:10},{id:'y',type:'stamp',member:'old',time:time-DAY,branchId:'a',saleAmount:30},{id:'z',type:'stamp',member:'ready',time:time-2*DAY,branchId:'b',saleAmount:null},{id:'undone',type:'stamp',member:'new',time,saleAmount:999,undone:true},{type:'redeem',member:'old',time:time-DAY,branchId:'a'}]};
const report=growthReport([reportShop],{time});assert.equal(report.metrics.sales,30);assert.equal(report.metrics.coverage,50);assert.equal(report.metrics.returning,1);assert.equal(report.metrics.returnRate,50);assert.equal(report.metrics.redeemed,1);assert.equal(report.segments.near,1);assert.equal(report.segments.ready,1);assert.equal(report.segments.new,1);
const branchReport=growthReport([reportShop],{time,branchId:'a'});assert.equal(branchReport.metrics.sales,30);assert.equal(branchReport.metrics.visits,1);assert.equal(branchReport.metrics.returnRate,100);
console.log('PASS: optional recorded-paid referral eligibility, undo grace period, exactly-once awards, historic reward preservation, catalog choices, points, rollback, branch metrics and missing amounts.');
