import {randomBytes,createHash,createCipheriv,createDecipheriv,timingSafeEqual} from 'node:crypto';
import {createRequire} from 'node:module';
import path from 'node:path';
import {buildVerificationMessage} from './email-message.mjs';
const sharp=createRequire(import.meta.url)('sharp');
export function createMailer({sql,origin,fail}){
  const provider=process.env.EMAIL_PROVIDER||'disabled';
  if(process.env.NODE_ENV==='production'&&provider==='test')throw Error('Test email is forbidden in production');
  sql.exec('CREATE TABLE IF NOT EXISTS mail_settings(id INTEGER PRIMARY KEY,json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS mail_oauth(state TEXT PRIMARY KEY,expires INTEGER NOT NULL);');
  const eq=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&x.length>0&&timingSafeEqual(x,y);};
  const key=()=>createHash('sha256').update(process.env.MAIL_TOKEN_KEY||fail('إعداد البريد غير مكتمل.',503)).digest();
  function seal(v){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv),body=Buffer.concat([c.update(v,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),body]).toString('base64');}
  function unseal(v){const b=Buffer.from(v,'base64'),c=createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));c.setAuthTag(b.subarray(12,28));return Buffer.concat([c.update(b.subarray(28)),c.final()]).toString('utf8');}
  const saved=()=>{const row=sql.prepare('SELECT json FROM mail_settings WHERE id=1').get();return row?JSON.parse(row.json):null;};
  const ready=()=>provider==='test'||provider==='gmail-api'&&!!(process.env.GMAIL_CLIENT_ID&&process.env.GMAIL_CLIENT_SECRET&&(process.env.GMAIL_REFRESH_TOKEN||saved()?.token));
  async function jsonFetch(url,options){const r=await fetch(url,{...options,signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)fail('تعذر الاتصال بخدمة البريد. حاول لاحقًا.',502);return data;}
  let logoPromise;
  function logo(){return logoPromise||=sharp(path.resolve('dist/brand-logo.png')).resize({width:480,withoutEnlargement:true}).flatten({background:'#ffffff'}).png({compressionLevel:9}).toBuffer().catch(()=>null);}
  async function send(to,code,purpose){if(provider==='test')return;if(!ready())fail('إرسال البريد قيد الإعداد. حاول لاحقًا.',503);const token=process.env.GMAIL_REFRESH_TOKEN||unseal(saved().token);const auth=await jsonFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:token,client_id:process.env.GMAIL_CLIENT_ID,client_secret:process.env.GMAIL_CLIENT_SECRET})});const sender=process.env.GMAIL_SENDER||saved()?.sender||process.env.ADMIN_EMAIL;const mime=buildVerificationMessage({sender,to,code,purpose,logo:await logo()});await jsonFetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{Authorization:'Bearer '+auth.access_token,'Content-Type':'application/json'},body:JSON.stringify({raw:Buffer.from(mime).toString('base64url')})});}
  function setup(url){if(!eq(url.searchParams.get('token'),process.env.MAIL_SETUP_TOKEN))fail('غير مسموح.',403);if(!process.env.GMAIL_CLIENT_ID||!process.env.GMAIL_CLIENT_SECRET||!process.env.MAIL_TOKEN_KEY)fail('أكمل إعدادات البريد في الاستضافة أولًا.',503);if(saved())fail('البريد مربوط بالفعل.',409);const state=randomBytes(32).toString('hex');sql.prepare('INSERT INTO mail_oauth VALUES(?,?)').run(state,Date.now()+600000);return 'https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:process.env.GMAIL_CLIENT_ID,redirect_uri:origin+'/mail/callback',response_type:'code',scope:'openid email https://www.googleapis.com/auth/gmail.send',access_type:'offline',prompt:'consent',state,login_hint:process.env.ADMIN_EMAIL});}
  async function callback(url){const state=url.searchParams.get('state')||'';const row=sql.prepare('SELECT * FROM mail_oauth WHERE state=?').get(state);if(!row||row.expires<Date.now())fail('جلسة الربط غير صالحة.',403);sql.prepare('DELETE FROM mail_oauth WHERE state=?').run(state);if(!url.searchParams.get('code'))fail('لم توافق على ربط البريد.');const auth=await jsonFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GMAIL_CLIENT_ID,client_secret:process.env.GMAIL_CLIENT_SECRET,code:url.searchParams.get('code'),grant_type:'authorization_code',redirect_uri:origin+'/mail/callback'})});const who=await jsonFetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:'Bearer '+auth.access_token}});if(who.email?.toLowerCase()!==process.env.ADMIN_EMAIL?.toLowerCase()||!who.email_verified||!auth.refresh_token)fail('استخدم بريد الإدارة المعتمد لربط الإرسال.',403);sql.prepare('INSERT OR REPLACE INTO mail_settings VALUES(1,?)').run(JSON.stringify({token:seal(auth.refresh_token),sender:who.email}));return who.email;}
  function exportToken(url){if(!eq(url.searchParams.get('token'),process.env.MAIL_SETUP_TOKEN))fail('غير مسموح.',403);const row=saved();if(!row)fail('لم يكتمل الربط.',404);return unseal(row.token);}
  return {send,ready,setup,callback,exportToken,provider};
}
