import fs from 'node:fs';import path from 'node:path';import {Worker} from 'node:worker_threads';import {monitorEventLoopDelay} from 'node:perf_hooks';
export function createOperations({sql,dataDir,fail}){
 const dir=path.join(dataDir,'backups');fs.mkdirSync(dir,{recursive:true});const delay=monitorEventLoopDelay({resolution:20});delay.enable();let pending=false,lastBackup=null,lastFailure=null;const requests=[];let errors=0;const started=Date.now();
 sql.exec('CREATE TABLE IF NOT EXISTS recovery_audit(id INTEGER PRIMARY KEY,shop TEXT NOT NULL,member TEXT NOT NULL,issuer_kind TEXT NOT NULL,issuer_id TEXT NOT NULL,event TEXT NOT NULL,time INTEGER NOT NULL);');
 function backup(){if(pending)return Promise.resolve({busy:true});pending=true;return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./backup-worker.mjs',import.meta.url),{workerData:{dataDir,dir,key:process.env.BACKUP_ENCRYPTION_KEY||''}});worker.once('message',result=>{pending=false;if(result.error){lastFailure={time:Date.now(),reason:'backup_failed'};reject(Error('تعذر إنشاء النسخة الاحتياطية.'));}else{lastBackup=result;lastFailure=null;resolve(result);}});worker.once('error',()=>{pending=false;lastFailure={time:Date.now(),reason:'backup_failed'};reject(Error('تعذر إنشاء النسخة الاحتياطية.'));});worker.once('exit',()=>{if(pending){pending=false;lastFailure={time:Date.now(),reason:'backup_failed'};reject(Error('تعذر إنشاء النسخة الاحتياطية.'));}});});}
 function snapshot(){const times=requests.map(x=>x.ms).sort((a,b)=>a-b),files=fs.readdirSync(dir).filter(x=>x.endsWith('.rgbackup'));return {uptimeSeconds:Math.floor((Date.now()-started)/1000),memoryMB:Math.round(process.memoryUsage().rss/1048576),eventLoopP95Ms:Math.round(delay.percentile(95)/1e6),requestsInWindow:requests.length,errorCount:errors,p95Ms:Math.round(times[Math.min(times.length-1,Math.ceil(times.length*.95)-1)]||0),databaseBytes:fs.statSync(path.join(dataDir,'rijaa.sqlite')).size,backup:{busy:pending,last:lastBackup,failure:lastFailure,count:files.length,encrypted:!!process.env.BACKUP_ENCRYPTION_KEY}};}
 function observe(req,res){const begin=performance.now();res.once('finish',()=>{const ms=performance.now()-begin;requests.push({ms,status:res.statusCode,time:Date.now()});while(requests.length>1000||requests[0]?.time<Date.now()-3600000)requests.shift();if(res.statusCode>=500)errors++;if(ms>1500||res.statusCode>=500)console.warn(JSON.stringify({event:'request_health',route:(req.url||'').split('?')[0],status:res.statusCode,ms:Math.round(ms)}));});}
 async function handle(req,res,url,principal){if(principal?.kind!=='admin')fail('الإجراء مخصص للإدارة.',403);if(req.method==='GET'&&url.pathname==='/api/operations/status')return snapshot();if(req.method==='GET'&&url.pathname==='/api/operations/recovery')return {rows:sql.prepare('SELECT shop,issuer_kind,issuer_id,event,time FROM recovery_audit ORDER BY time DESC LIMIT 100').all()};if(req.method==='POST'&&url.pathname==='/api/operations/backup')return backup();fail('المسار غير موجود.',404);}
 const timer=setInterval(()=>backup().catch(()=>console.error(JSON.stringify({event:'backup_failed'}))),24*3600000);timer.unref();setTimeout(()=>backup().catch(()=>console.error(JSON.stringify({event:'backup_failed'}))),5000).unref();return {handle,observe,snapshot,backup};
}
