import {randomBytes,randomUUID} from 'node:crypto';
export function createSupport({sql,load,hash,rate,fail,authorized,production=false}){
 sql.exec(`CREATE TABLE IF NOT EXISTS support_tickets(id TEXT PRIMARY KEY,reference TEXT UNIQUE NOT NULL,owner_key TEXT NOT NULL,owner_kind TEXT NOT NULL,owner_name TEXT NOT NULL,email TEXT NOT NULL,subject TEXT NOT NULL,category TEXT NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL,updated INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS support_owner_updated ON support_tickets(owner_key,updated DESC); CREATE TABLE IF NOT EXISTS support_messages(id TEXT PRIMARY KEY,ticket TEXT NOT NULL,author TEXT NOT NULL,body TEXT NOT NULL,time INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS support_ticket_messages ON support_messages(ticket,time);`);
 sql.exec('CREATE TABLE IF NOT EXISTS support_read_receipts(ticket TEXT NOT NULL,reader TEXT NOT NULL,seen INTEGER NOT NULL,PRIMARY KEY(ticket,reader));');
 const categories=new Set(['technical','billing','design','privacy','complaint','other']),statuses=new Set(['open','waiting','closed']);
 const clean=(v,max)=>{if(typeof v!=='string'||v.trim().length>max)fail('راجع البيانات وحدود النص.');return v.trim();};
 function context(req,res,principal,create=false){
  if(principal){if(principal.kind==='admin')return {key:'admin:'+principal.account,kind:'admin',name:'إدارة رِجعة',email:''};const s=load(),sh=authorized(s,principal,false);let who;if(principal.kind==='owner'){who=s.accounts.find(a=>a.id===principal.account);if(!who)fail('الحساب غير متاح.',403);}else if(principal.kind==='employee'){const base=s.shops.find(x=>x.id===(sh.business||sh.id));who=base.employees.find(e=>e.id===principal.employee&&e.status==='active');}else if(principal.kind==='customer')who=sh.members.find(m=>m.id===principal.member);if(!who)fail('الحساب غير متاح.',403);return {key:principal.kind+':'+(principal.account||principal.employee||principal.shop+':'+principal.member),kind:principal.kind,name:who.name||'مستخدم رِجعة',email:who.email||''};}
  let token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('rijaa_support='))?.slice(14);if(!/^[a-f0-9]{64}$/.test(token||'')){if(!create)return {key:'',kind:'guest',name:'',email:''};token=randomBytes(32).toString('hex');const cookie=`rijaa_support=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=2592000${production?'; Secure':''}`;const prior=res.getHeader('Set-Cookie');res.setHeader('Set-Cookie',prior?[].concat(prior,cookie):cookie);}return {key:'guest:'+hash(token),kind:'guest',name:'',email:''};
 }
 const summary=t=>({id:t.id,reference:t.reference,name:t.owner_name,email:t.email,kind:t.owner_kind,subject:t.subject,category:t.category,status:t.status,created:t.created,updated:t.updated});
 function ticket(id,c){const t=sql.prepare('SELECT * FROM support_tickets WHERE id=?').get(id);if(!t||(c.kind!=='admin'&&t.owner_key!==c.key))fail('التذكرة غير متاحة.',404);return t;}
 function detail(t){return {...summary(t),messages:sql.prepare('SELECT author,body,time FROM support_messages WHERE ticket=? ORDER BY time,rowid').all(t.id)};}
 function transaction(fn){sql.exec('BEGIN IMMEDIATE');try{const r=fn();sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}
 async function parse(req){let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>65536)fail('الطلب كبير جدًا.',413);}try{return JSON.parse(raw||'{}');}catch{fail('طلب غير صحيح.');}}
 async function handle(req,res,url,principal,ip){rate('support-request:'+ip,180,60000);const c=context(req,res,principal,req.method==='POST'&&url.pathname==='/api/support/create');
  if(req.method==='GET'&&url.pathname==='/api/support/summary'){const reader=c.kind==='admin'?'admin':c.key,author=c.kind==='admin'?'customer':'support',scope=c.kind==='admin'?'':' AND t.owner_key=?',args=c.kind==='admin'?[author,reader]:[author,reader,c.key];const row=sql.prepare(`SELECT count(*) AS unread FROM support_tickets t WHERE t.status!='closed' AND EXISTS(SELECT 1 FROM support_messages m WHERE m.ticket=t.id AND m.author=? AND m.time>COALESCE((SELECT seen FROM support_read_receipts r WHERE r.ticket=t.id AND r.reader=?),0))${scope}`).get(...args);return {kind:c.kind,unread:row.unread};}
  if(req.method==='GET'&&url.pathname==='/api/support/tickets'){const offset=Math.max(0,Math.min(100000,Number(url.searchParams.get('offset'))||0)),conditions=[],args=[];if(c.kind!=='admin'){conditions.push('owner_key=?');args.push(c.key);}const filter=url.searchParams.get('status');if(statuses.has(filter)){conditions.push('status=?');args.push(filter);}const q=(url.searchParams.get('q')||'').slice(0,120);if(q){conditions.push('(subject LIKE ? OR reference LIKE ? OR owner_name LIKE ?)');args.push('%'+q+'%','%'+q+'%','%'+q+'%');}const where=conditions.length?' WHERE '+conditions.join(' AND '):'';const total=sql.prepare('SELECT count(*) AS n FROM support_tickets'+where).get(...args).n;const rows=sql.prepare('SELECT * FROM support_tickets'+where+' ORDER BY updated DESC LIMIT 50 OFFSET ?').all(...args,Math.floor(offset));return {kind:c.kind,name:c.name,total,tickets:rows.map(summary)};}
  if(req.method==='GET'&&url.pathname==='/api/support/ticket')return {ticket:detail(ticket(url.searchParams.get('id')||'',c))};
  if(req.method!=='POST')fail('المسار غير موجود.',404);const b=await parse(req);
  if(url.pathname==='/api/support/create'){rate('support-create-ip:'+ip,5,3600000);rate('support-create-owner:'+c.key,5,3600000);const subject=clean(b.subject,120),message=clean(b.message,4000),name=c.kind==='guest'?clean(b.name,60):c.name,email=c.kind==='guest'?clean(b.email,254):c.email;if(subject.length<4||message.length<10||!name||(c.kind==='guest'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)))fail('أدخل الاسم وبيانات التواصل وعنوانًا ووصفًا واضحين.');if(!categories.has(b.category))fail('اختر نوع الطلب.');const id=randomUUID(),reference='RJ-'+randomBytes(6).toString('hex').toUpperCase(),time=Date.now();transaction(()=>{sql.prepare('INSERT INTO support_tickets VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,reference,c.key,c.kind,name,email,subject,b.category,'open',time,time);sql.prepare('INSERT INTO support_messages VALUES(?,?,?,?,?)').run(randomUUID(),id,'customer',message,time);});return {ticket:detail(ticket(id,c))};}
  const t=ticket(String(b.id||''),c);
  if(url.pathname==='/api/support/seen'){const latest=sql.prepare('SELECT max(time) AS seen FROM support_messages WHERE ticket=?').get(t.id).seen||0;const seen=Math.min(latest,Math.max(0,Number(b.seen)||0));sql.prepare('INSERT INTO support_read_receipts VALUES(?,?,?) ON CONFLICT(ticket,reader) DO UPDATE SET seen=MAX(seen,excluded.seen)').run(t.id,c.kind==='admin'?'admin':c.key,seen);return {ok:true};}
  if(url.pathname==='/api/support/reply'){rate('support-reply:'+c.key,30,600000);const message=clean(b.message,4000);if(!message)fail('اكتب الرد أولًا.');const time=Date.now();transaction(()=>{sql.prepare('INSERT INTO support_messages VALUES(?,?,?,?,?)').run(randomUUID(),t.id,c.kind==='admin'?'support':'customer',message,time);sql.prepare('UPDATE support_tickets SET status=?,updated=? WHERE id=?').run(c.kind==='admin'?'waiting':'open',time,t.id);});return {ticket:detail(ticket(t.id,c))};}
  if(url.pathname==='/api/support/status'){if(c.kind!=='admin')fail('الإجراء مخصص للإدارة.',403);if(!statuses.has(b.status))fail('حالة غير صحيحة.');sql.prepare('UPDATE support_tickets SET status=?,updated=? WHERE id=?').run(b.status,Date.now(),t.id);return {ticket:detail(ticket(t.id,c))};}
  fail('المسار غير موجود.',404);
 }
 return {handle};
}
