import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {walletImages} from './wallet-images.mjs';
const Loyalty=createRequire(import.meta.url)('./dist/loyalty.js'),BASE='https://api.walletwallet.dev';
export function createWallet({sql,load,authorized,staffAllows,status,accountFor,fail,rate,dataDir,origin,request=fetch}){
 sql.exec("CREATE TABLE IF NOT EXISTS wallet_passes(shop TEXT NOT NULL,member TEXT NOT NULL,serial TEXT,google_url TEXT,share_url TEXT,apple BLOB,payload_hash TEXT,status TEXT NOT NULL DEFAULT 'new',dirty INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,next_attempt INTEGER NOT NULL DEFAULT 0,last_error TEXT,updated INTEGER,PRIMARY KEY(shop,member));");
 sql.prepare("UPDATE wallet_passes SET status='uncertain',last_error='creation_uncertain' WHERE status='issuing'").run();
 const locks=new Map();let draining=false;
 function configured(){return /^ww_live_[a-f0-9]{32}$/i.test(process.env.WALLETWALLET_API_KEY||'');}
 async function provider(route,method='GET',payload){if(!configured())fail('ربط Wallet غير مهيأ.',503);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const r=await request(BASE+route,{method,headers:{Authorization:'Bearer '+process.env.WALLETWALLET_API_KEY,...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined,signal:controller.signal});const result=await r.json();if(!r.ok){const messages={400:'رفض المزود تنسيق البطاقة أو صورها.',401:'مفتاح Wallet غير صالح.',403:'خطة Wallet لا تدعم هذا الإجراء.',404:'بطاقة Wallet غير موجودة عند المزود.',429:'وصلت إلى حصة Wallet الشهرية.'};throw Object.assign(Error(messages[r.status]||'تعذر الاتصال بمزود Wallet.'),{status:502,providerStatus:r.status});}return result;}finally{clearTimeout(timer);}}
 function cardFor(principal,body){const s=load();if(!principal)fail('سجّل الدخول أولًا.',401);const sh=s.shops.find(x=>x.id===(body.shop||principal.shop));if(!sh||sh.archivedAt||sh.status!=='active'||status(accountFor(s,sh))!=='active')fail('البطاقة غير متاحة.',403);
  if(principal.kind==='customer'){if(principal.shop!==sh.id)fail('البطاقة لا تخصك.',403);const member=sh.members.find(x=>x.id===principal.member);if(!member)fail('العضوية غير موجودة.',404);return {sh,member};}
  if(!['owner','admin'].includes(principal.kind))fail('هذا الإجراء غير مسموح.',403);if(principal.kind==='owner'){const base=authorized(s,principal,true);if((base.business||base.id)!==(sh.business||sh.id))fail('البطاقة لا تخص نشاطك.',403);}if(principal.kind==='admin'&&body.scope&&body.scope!==(sh.business||sh.id))fail('البطاقة خارج نطاق المعاينة.',403);
  if(body.preview!==true)fail('إصدار العضوية الفعلية يتم من جلسة العميل.',403);return {sh,member:{id:'DEMO-WALLET-'+sh.id,stamps:2,points:20,rewards:0},preview:true};
 }
 async function payload(sh,member,preview){const c=sh.card,p=Loyalty.program(c),en=c.cardLanguage==='en',balance=p.type==='points'?member.points||0:member.stamps||0,target=p.type==='points'?p.pointsCost:c.target;return {barcodeValue:member.id,barcodeFormat:p.barcodeFormat==='code128'?'Code128':'QR',barcodeAltText:'',logoText:(c.name||c.title||sh.name).slice(0,64),organizationName:(c.title||sh.name).slice(0,64),description:(preview?'Test · ':'')+(c.title||sh.name).slice(0,100),sharingProhibited:true,color:c.color,colorPreset:'green',primaryFields:[{label:en?'REWARD':'المكافأة',value:String(Loyalty.label(c)||'').slice(0,256)}],headerFields:[{label:en?'BALANCE':'الرصيد',value:balance+' / '+target,changeMessage:en?'Your balance: %@':'رصيدك الآن: %@'}],secondaryFields:[{label:en?'AVAILABLE REWARDS':'مكافآت جاهزة',value:String(Loyalty.available(member,c))}],backFields:[{label:en?'TERMS':'الشروط',value:String(c.terms||'').slice(0,256)},{label:en?'PRIVACY':'الخصوصية',value:origin+'/privacy.html'},...(preview?[{label:'TEST',value:'Preview only. Barcode cannot earn rewards.'}]:[])],...await walletImages(c,member,dataDir)};}
 function publicRow(row){return {ready:!!row?.serial,status:row?.status||'new',appleAvailable:!!row?.apple?.length,googleSaveUrl:row?.google_url||'',shareUrl:row?.share_url||'',updated:row?.updated||null,error:row?.last_error||null};}
 async function sync(sh,member,preview=false){const key=sh.id+':'+member.id;if(locks.has(key))return locks.get(key);const job=(async()=>{sql.prepare('INSERT OR IGNORE INTO wallet_passes(shop,member) VALUES(?,?)').run(sh.id,member.id);let row=sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id);if(['uncertain','issuing'].includes(row.status))fail('نتيجة إصدار البطاقة غير مؤكدة. تواصل مع الدعم قبل إعادة الإصدار.',409);let body;try{body=await payload(sh,member,preview);}catch(e){fail(e.message,422);}const hash=createHash('sha256').update(JSON.stringify(body)).digest('hex'),revision=row.dirty;if(row.serial&&row.payload_hash===hash){sql.prepare("UPDATE wallet_passes SET dirty=0,status='ready' WHERE shop=? AND member=? AND dirty=?").run(sh.id,member.id,revision);return publicRow({...row,status:'ready'});}
  try{if(!row.serial){sql.prepare("UPDATE wallet_passes SET status='issuing' WHERE shop=? AND member=?").run(sh.id,member.id);const result=await provider('/api/passes','POST',body);if(!result.serialNumber||!result.applePass||!/^https:\/\/pay.google.com\//.test(result.googleSaveUrl||''))throw Error('استجابة Wallet غير مكتملة.');const apple=Buffer.from(result.applePass,'base64');if(apple.length>10485760||apple.subarray(0,2).toString()!=='PK')throw Error('ملف Wallet غير صالح.');sql.prepare("UPDATE wallet_passes SET serial=?,google_url=?,share_url=?,apple=?,payload_hash=?,status='ready',attempts=0,last_error=NULL,updated=?,next_attempt=0 WHERE shop=? AND member=?").run(result.serialNumber,result.googleSaveUrl,result.shareUrl||'',apple,hash,Date.now(),sh.id,member.id);}
   else{await provider('/api/passes/'+encodeURIComponent(row.serial),'PUT',body);sql.prepare("UPDATE wallet_passes SET payload_hash=?,status='ready',attempts=0,last_error=NULL,updated=?,next_attempt=0 WHERE shop=? AND member=?").run(hash,Date.now(),sh.id,member.id);}
   if(revision===row.dirty)sql.prepare('UPDATE wallet_passes SET dirty=0 WHERE shop=? AND member=? AND dirty=?').run(sh.id,member.id,revision);return publicRow(sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id));
  }catch(e){const uncertain=!row.serial&&(!e.providerStatus||e.providerStatus>=500);sql.prepare('UPDATE wallet_passes SET status=?,attempts=attempts+1,last_error=?,next_attempt=? WHERE shop=? AND member=?').run(uncertain?'uncertain':row.serial?'retry':'new',e.providerStatus?'provider_'+e.providerStatus:'connection_failed',Date.now()+Math.min(3600000,30000*2**Math.min(row.attempts,7)),sh.id,member.id);throw e;}
 })();locks.set(key,job);try{return await job;}finally{locks.delete(key);}}
 function enqueue(shop){sql.prepare("UPDATE wallet_passes SET dirty=dirty+1,next_attempt=0 WHERE shop=? AND serial IS NOT NULL AND member NOT LIKE 'DEMO-WALLET-%'").run(shop);}
 async function drain(){if(draining||!configured())return;draining=true;try{for(const row of sql.prepare('SELECT * FROM wallet_passes WHERE dirty>0 AND serial IS NOT NULL AND next_attempt<=? LIMIT 10').all(Date.now())){const s=load(),sh=s.shops.find(x=>x.id===row.shop),member=sh?.members.find(x=>x.id===row.member);if(!sh||!member||sh.archivedAt||sh.status!=='active'||status(accountFor(s,sh))!=='active'){sql.prepare("UPDATE wallet_passes SET status='suspended',dirty=0 WHERE shop=? AND member=?").run(row.shop,row.member);continue;}try{await sync(sh,member);}catch(e){console.warn(JSON.stringify({event:'wallet_update_failed',status:e.providerStatus||0}));}}}finally{draining=false;}}
 async function handle(req,res,url,principal,body={}){if(url.pathname==='/api/wallet/status'){const {sh,member}=cardFor(principal,body.shop?body:{shop:url.searchParams.get('shop'),preview:url.searchParams.get('preview')==='1',scope:url.searchParams.get('scope')});return {configured:configured(),...publicRow(sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id))};}
  if(url.pathname==='/api/wallet/usage'){if(principal?.kind!=='admin')fail('خاص بالإدارة.',403);return provider('/api/auth/usage');}
  if(req.method==='POST'&&url.pathname==='/api/wallet/issue'){rate('wallet:'+JSON.stringify(principal),20,60000);const {sh,member,preview}=cardFor(principal,body);return sync(sh,member,preview);}
  if(req.method==='GET'&&url.pathname==='/api/wallet/apple'){const {sh,member}=cardFor(principal,{shop:url.searchParams.get('shop'),preview:url.searchParams.get('preview')==='1',scope:url.searchParams.get('scope')});const row=sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id);if(!row?.apple||row.status==='revoked')fail('أصدر البطاقة أولًا.',404);res.writeHead(200,{'Content-Type':'application/vnd.apple.pkpass','Content-Disposition':'attachment; filename="loyalty.pkpass"','Cache-Control':'no-store'});res.end(row.apple);return null;}fail('المسار غير موجود.',404);}
 setInterval(drain,2000).unref();return {handle,enqueue,configured,provider,sync,drain};
}
