import {createRequire as engagementRequire} from 'node:module';
const Engagement=engagementRequire(import.meta.url)('./dist/engagement.js');
import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {walletImages} from './wallet-images.mjs';import {walletFields,WALLET_LAYOUT_VERSION} from './wallet-fields.mjs';
const Loyalty=createRequire(import.meta.url)('./dist/loyalty.js'),BASE='https://api.walletwallet.dev';
export function createWallet({sql,load,authorized,staffAllows,status,accountFor,fail,rate,dataDir,origin,request=fetch}){
 sql.exec("CREATE TABLE IF NOT EXISTS wallet_passes(shop TEXT NOT NULL,member TEXT NOT NULL,serial TEXT,google_url TEXT,share_url TEXT,apple BLOB,payload_hash TEXT,status TEXT NOT NULL DEFAULT 'new',dirty INTEGER NOT NULL DEFAULT 0,attempts INTEGER NOT NULL DEFAULT 0,next_attempt INTEGER NOT NULL DEFAULT 0,last_error TEXT,updated INTEGER,PRIMARY KEY(shop,member));");
 sql.prepare("UPDATE wallet_passes SET status='uncertain',last_error='creation_uncertain' WHERE status='issuing'").run();
 sql.exec("CREATE TABLE IF NOT EXISTS wallet_layout_versions(version TEXT PRIMARY KEY);");if(!sql.prepare('SELECT version FROM wallet_layout_versions WHERE version=?').get('apple-poster-v2')){sql.exec('BEGIN');try{sql.prepare("UPDATE wallet_passes SET dirty=dirty+1,next_attempt=0 WHERE serial IS NOT NULL AND member NOT LIKE 'DEMO-WALLET-%'").run();sql.prepare('INSERT INTO wallet_layout_versions(version) VALUES(?)').run('apple-poster-v2');sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}}const locks=new Map();let draining=false;
 function configured(){return /^ww_live_[a-f0-9]{32}$/i.test(process.env.WALLETWALLET_API_KEY||'');}
 async function provider(route,method='GET',payload){if(!configured())fail('ربط Wallet غير مهيأ.',503);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const r=await request(BASE+route,{method,headers:{Authorization:'Bearer '+process.env.WALLETWALLET_API_KEY,...(payload?{'Content-Type':'application/json'}:{})},body:payload?JSON.stringify(payload):undefined,signal:controller.signal});const result=await r.json();if(!r.ok){if(r.status===400){const reason=String(result.error||result.message||'');console.warn(JSON.stringify({event:'wallet_provider_validation',fields:[...new Set(reason.match(/logoText|primaryFields|secondaryFields|footerFields|headerFields|backgroundURL|stripURL|logoURL|title|barcodeValue/g)||[])],required:/require|missing|at least|provide/i.test(reason),plan:/plan|upgrade|pro feature/i.test(reason)}));}const messages={400:'رفض المزود تنسيق البطاقة أو صورها.',401:'مفتاح Wallet غير صالح.',403:'خطة Wallet لا تدعم هذا الإجراء.',404:'بطاقة Wallet غير موجودة عند المزود.',429:'وصلت إلى حصة Wallet الشهرية.'};throw Object.assign(Error(messages[r.status]||'تعذر الاتصال بمزود Wallet.'),{status:502,providerStatus:r.status});}return result;}finally{clearTimeout(timer);}}
 function cardFor(principal,body){const s=load();if(!principal)fail('سجّل الدخول أولًا.',401);const sh=s.shops.find(x=>x.id===(body.shop||principal.shop));if(!sh||sh.archivedAt||sh.status!=='active'||status(accountFor(s,sh))!=='active')fail('البطاقة غير متاحة.',403);
  if(principal.kind==='customer'){if(principal.shop!==sh.id)fail('البطاقة لا تخصك.',403);const member=sh.members.find(x=>x.id===principal.member);if(!member)fail('العضوية غير موجودة.',404);return {sh,member};}
  if(!['owner','admin'].includes(principal.kind))fail('هذا الإجراء غير مسموح.',403);if(principal.kind==='owner'){const base=authorized(s,principal,true);if((base.business||base.id)!==(sh.business||sh.id))fail('البطاقة لا تخص نشاطك.',403);}if(principal.kind==='admin'&&body.scope&&body.scope!==(sh.business||sh.id))fail('البطاقة خارج نطاق المعاينة.',403);
  if(body.preview!==true)fail('إصدار العضوية الفعلية يتم من جلسة العميل.',403);return {sh,member:{id:'DEMO-WALLET-'+sh.id,stamps:2,points:20,rewards:0},preview:true};
 }
 // The provider requires nonempty textual identity even for logo-only passes.
 // A zero-width logo text preserves the logo-only appearance and leaves the strip free of primary text.
 // organizationName and description still supply a readable issuer and accessibility text.
 async function payload(sh,member,preview){const membership=Engagement.level(sh,member);const c=sh.card,p=Loyalty.program(c),en=c.cardLanguage==='en',{rewardAvailability,...fields}=walletFields(c,member);return {barcodeValue:member.id,barcodeFormat:p.barcodeFormat==='code128'?'Code128':'QR',barcodeAltText:'',logoText:c.logo?'\u200B':String(c.name||sh.name||'برنامج الولاء').slice(0,64),organizationName:String(c.name||'برنامج الولاء').slice(0,64),description:preview?'Test loyalty card':'Loyalty card',sharingProhibited:true,color:c.color,colorPreset:'green',...fields,backFields:[rewardAvailability,...(membership?[{label:en?'MEMBERSHIP LEVEL':'مستوى الولاء',value:membership.name+(membership.benefit?' — '+membership.benefit:'')}]:[]),{label:en?'TERMS':'الشروط',value:String(c.terms||'').slice(0,256)},{label:en?'PRIVACY':'الخصوصية',value:origin+'/privacy.html'},...(c.rewardChoices?.length?[{label:en?'REWARD OPTIONS':'خيارات المكافأة',value:c.rewardChoices.map(x=>x.label).join(' · ')+' — '+(en?'Choose on your card page or with staff.':'اختر في صفحة بطاقتك أو لدى الموظف.')}]:[]),...(preview?[{label:'TEST',value:'Preview only. Barcode cannot earn rewards.'}]:[])],...await walletImages(c,member,dataDir)};}
 // Queue the one-time upgrade only after the provider accepts the new layout.
 // Existing passes keep their serials; repeated starts or identical syncs cost no calls.
 function activateLayoutMigration(){if(sql.prepare('SELECT version FROM wallet_layout_versions WHERE version=?').get(WALLET_LAYOUT_VERSION))return;sql.exec('BEGIN');try{const result=sql.prepare("UPDATE wallet_passes SET dirty=dirty+1,next_attempt=0 WHERE serial IS NOT NULL AND member NOT LIKE 'DEMO-WALLET-%'").run();sql.prepare('INSERT INTO wallet_layout_versions(version) VALUES(?)').run(WALLET_LAYOUT_VERSION);sql.exec('COMMIT');console.info(JSON.stringify({event:'wallet_layout_upgrade_queued',version:WALLET_LAYOUT_VERSION,passes:Number(result.changes)}));}catch(e){sql.exec('ROLLBACK');throw e;}}
 function publicRow(row){return {ready:!!row?.serial,status:row?.status||'new',appleAvailable:!!row?.apple?.length,googleSaveUrl:row?.serial?BASE+'/api/passes/'+encodeURIComponent(row.serial)+'/google':'',shareUrl:row?.share_url||'',updated:row?.updated||null,error:row?.last_error||null};}
 async function sync(sh,member,preview=false){const key=sh.id+':'+member.id;if(locks.has(key))return locks.get(key);const job=(async()=>{sql.prepare('INSERT OR IGNORE INTO wallet_passes(shop,member) VALUES(?,?)').run(sh.id,member.id);let row=sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id);if(['uncertain','issuing'].includes(row.status))fail('نتيجة إصدار البطاقة غير مؤكدة. تواصل مع الدعم قبل إعادة الإصدار.',409);let body;try{body=await payload(sh,member,preview);}catch(e){fail(e.message,422);}const hash=createHash('sha256').update(JSON.stringify(body)).digest('hex'),revision=row.dirty;if(row.serial&&row.payload_hash===hash){activateLayoutMigration();sql.prepare("UPDATE wallet_passes SET dirty=0,status='ready' WHERE shop=? AND member=? AND dirty=?").run(sh.id,member.id,revision);return publicRow({...row,status:'ready'});}
  try{if(!row.serial){sql.prepare("UPDATE wallet_passes SET status='issuing' WHERE shop=? AND member=?").run(sh.id,member.id);const result=await provider('/api/passes','POST',body);if(!result.serialNumber||!result.applePass||!/^https:\/\/pay.google.com\//.test(result.googleSaveUrl||''))throw Error('استجابة Wallet غير مكتملة.');const apple=Buffer.from(result.applePass,'base64');if(apple.length>10485760||apple.subarray(0,2).toString()!=='PK')throw Error('ملف Wallet غير صالح.');sql.prepare("UPDATE wallet_passes SET serial=?,google_url=?,share_url=?,apple=?,payload_hash=?,status='ready',attempts=0,last_error=NULL,updated=?,next_attempt=0 WHERE shop=? AND member=?").run(result.serialNumber,result.googleSaveUrl,result.shareUrl||'',apple,hash,Date.now(),sh.id,member.id);}
   else{await provider('/api/passes/'+encodeURIComponent(row.serial),'PUT',body);sql.prepare("UPDATE wallet_passes SET payload_hash=?,status='ready',attempts=0,last_error=NULL,updated=?,next_attempt=0 WHERE shop=? AND member=?").run(hash,Date.now(),sh.id,member.id);}
   activateLayoutMigration();if(revision===row.dirty)sql.prepare('UPDATE wallet_passes SET dirty=0 WHERE shop=? AND member=? AND dirty=?').run(sh.id,member.id,revision);return publicRow(sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id));
  }catch(e){const uncertain=!row.serial&&(!e.providerStatus||e.providerStatus>=500);sql.prepare('UPDATE wallet_passes SET status=?,attempts=attempts+1,last_error=?,next_attempt=? WHERE shop=? AND member=?').run(uncertain?'uncertain':row.serial?'retry':'new',e.providerStatus?'provider_'+e.providerStatus:'connection_failed',Date.now()+Math.min(3600000,30000*2**Math.min(row.attempts,7)),sh.id,member.id);throw e;}
 })();locks.set(key,job);try{return await job;}finally{locks.delete(key);}}
 function enqueue(shop){sql.prepare("UPDATE wallet_passes SET dirty=dirty+1,next_attempt=0 WHERE shop=? AND serial IS NOT NULL AND member NOT LIKE 'DEMO-WALLET-%'").run(shop);}
 async function drain(){if(draining||!configured())return;draining=true;try{for(const row of sql.prepare('SELECT * FROM wallet_passes WHERE dirty>0 AND serial IS NOT NULL AND next_attempt<=? LIMIT 10').all(Date.now())){const s=load(),sh=s.shops.find(x=>x.id===row.shop),member=sh?.members.find(x=>x.id===row.member);if(!sh||!member||sh.archivedAt||sh.status!=='active'||status(accountFor(s,sh))!=='active'){sql.prepare("UPDATE wallet_passes SET status='suspended',dirty=0 WHERE shop=? AND member=?").run(row.shop,row.member);continue;}try{await sync(sh,member);}catch(e){console.warn(JSON.stringify({event:'wallet_update_failed',status:e.providerStatus||0}));}}}finally{draining=false;}}
 async function handle(req,res,url,principal,body={}){if(url.pathname==='/api/wallet/status'){const {sh,member}=cardFor(principal,body.shop?body:{shop:url.searchParams.get('shop'),preview:url.searchParams.get('preview')==='1',scope:url.searchParams.get('scope')});return {configured:configured(),...publicRow(sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id))};}
  if(url.pathname==='/api/wallet/usage'){if(principal?.kind!=='admin')fail('خاص بالإدارة.',403);const usage=await provider('/api/auth/usage');return {...usage,compatibility:{version:WALLET_LAYOUT_VERSION,enabled:!!sql.prepare('SELECT version FROM wallet_layout_versions WHERE version=?').get(WALLET_LAYOUT_VERSION),pending:sql.prepare("SELECT count(*) n FROM wallet_passes WHERE serial IS NOT NULL AND member NOT LIKE 'DEMO-WALLET-%' AND dirty>0").get().n,retrying:sql.prepare("SELECT count(*) n FROM wallet_passes WHERE serial IS NOT NULL AND member NOT LIKE 'DEMO-WALLET-%' AND dirty>0 AND status='retry'").get().n}};}
  if(req.method==='POST'&&url.pathname==='/api/wallet/issue'){rate('wallet:'+JSON.stringify(principal),20,60000);const {sh,member,preview}=cardFor(principal,body);return sync(sh,member,preview);}
  if(req.method==='GET'&&url.pathname==='/api/wallet/apple'){const {sh,member}=cardFor(principal,{shop:url.searchParams.get('shop'),preview:url.searchParams.get('preview')==='1',scope:url.searchParams.get('scope')});const row=sql.prepare('SELECT * FROM wallet_passes WHERE shop=? AND member=?').get(sh.id,member.id);if(!row?.apple||row.status==='revoked')fail('أصدر البطاقة أولًا.',404);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);let apple;try{const response=await request(BASE+'/p/'+encodeURIComponent(row.serial)+'/apple.pkpass',{signal:controller.signal});if(!response.ok)fail('تعذر تنزيل أحدث بطاقة Wallet. حاول مجددًا.',502);const chunks=[];let length=0;for await(const chunk of response.body){length+=chunk.length;if(length>10485760){controller.abort();fail('ملف Wallet أكبر من الحد المدعوم.',502);}chunks.push(Buffer.from(chunk));}apple=Buffer.concat(chunks);if(apple.subarray(0,2).toString()!=='PK')fail('ملف Wallet غير صالح.',502);}finally{clearTimeout(timer);}res.writeHead(200,{'Content-Type':'application/vnd.apple.pkpass','Content-Disposition':'attachment; filename="loyalty.pkpass"','Cache-Control':'no-store'});res.end(apple);return null;}fail('المسار غير موجود.',404);}
 setInterval(drain,2000).unref();return {handle,enqueue,configured,provider,sync,drain};
}
