import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {createWallet} from './wallet.mjs';
const root=fs.mkdtempSync(path.resolve('wallet-check-')),sql=new DatabaseSync(path.join(root,'test.sqlite')),designs=JSON.parse(fs.readFileSync('dist/showcase-designs.json')).slice(0,3);
const shops=designs.map((card,i)=>({id:'shop-'+i,card,status:'active',members:[{id:'RJ-'+i,points:20,stamps:2,rewards:0,name:'PRIVATE NAME',phone:'PRIVATE PHONE'}]})),calls=[];
process.env.WALLETWALLET_API_KEY='ww_live_'+'0'.repeat(32);
const wallet=createWallet({sql,dataDir:root,origin:'https://rg3h.cc',load:()=>({shops}),authorized:()=>shops[0],staffAllows:()=>true,status:()=> 'active',accountFor:()=>({}),rate(){},fail(message,status){throw Object.assign(Error(message),{status})},request:async(url,options)=>{if(url.endsWith('/apple.pkpass'))return new Response(Buffer.from('PK-latest-balance'));const body=options.body&&JSON.parse(options.body);calls.push({url,method:options.method,body});return {ok:true,json:async()=>({serialNumber:'serial-'+calls.length,applePass:Buffer.from('PK-mock-signed-pass').toString('base64'),googleSaveUrl:'https://pay.google.com/gp/v/save/test',shareUrl:'https://api.walletwallet.dev/p/test'})};}});
for(const sh of shops){const m=sh.members[0];await Promise.all([wallet.sync(sh,m),wallet.sync(sh,m)]);const body=calls.at(-1).body;assert.equal(body.barcodeValue,m.id);assert.deepEqual(body.primaryFields,[],'classic artwork must not have an oversized title');assert.deepEqual(body.secondaryFields,body.footerFields,'reward remains at the bottom of the poster and below the classic strip');assert(body.backFields.some(f=>f.label==='AVAILABLE REWARDS'||f.label==='مكافآت جاهزة'));if(sh.card.logo)assert.equal(body.logoText,'\u200B');assert(!JSON.stringify(body).includes('PRIVATE'));assert(body.backgroundURL.startsWith('data:image/png;base64,'));assert(body.stripURL.startsWith('data:image/png;base64,'));assert(Buffer.byteLength(JSON.stringify(body))<2097152);await wallet.sync(sh,m);}
assert.equal(calls.length,3);shops[0].card.title='Internal title only';shops[0].card.logoX=123;shops[0].card.balanceStyle='neon';await wallet.sync(shops[0],shops[0].members[0]);assert.equal(calls.length,3,'internal title and unsupported options must not consume quota');shops[0].members[0].stamps=3;wallet.enqueue('shop-0');await wallet.drain();assert.equal(calls.length,4);assert.equal(calls[3].method,'PUT');assert.equal(calls[3].body.headerFields[0].value,'3 / 4');wallet.enqueue('shop-0');await wallet.drain();assert.equal(calls.length,4);assert.equal(sql.prepare('SELECT dirty FROM wallet_passes WHERE shop=?').get('shop-0').dirty,0);
await assert.rejects(wallet.handle({method:'POST'},{},new URL('https://rg3h.cc/api/wallet/issue'),{kind:'customer',shop:'shop-0',member:'RJ-0'},{shop:'shop-1'}),{status:403});
await assert.rejects(wallet.handle({method:'POST'},{},new URL('https://rg3h.cc/api/wallet/issue'),{kind:'owner',shop:'shop-0'},{shop:'shop-1',preview:true}),{status:403});
let downloaded;await wallet.handle({method:'GET'},{writeHead(){},end(bytes){downloaded=bytes}},new URL('https://rg3h.cc/api/wallet/apple?shop=shop-0'),{kind:'customer',shop:'shop-0',member:'RJ-0'});assert.equal(downloaded.toString(),'PK-latest-balance');const latest=await wallet.handle({method:'GET'},{},new URL('https://rg3h.cc/api/wallet/status?shop=shop-0'),{kind:'customer',shop:'shop-0',member:'RJ-0'});assert.equal(latest.googleSaveUrl,'https://api.walletwallet.dev/api/passes/serial-1/google');shops[0].status='paused';wallet.enqueue('shop-0');await wallet.drain();assert.equal(sql.prepare('SELECT status FROM wallet_passes WHERE shop=?').get('shop-0').status,'suspended');assert.equal(calls.length,4);
shops[1].card.rewardChoices=[{id:'a',label:'Coffee'},{id:'b',label:'Cake'}];shops[1].card.cardLanguage='en';shops[1].card.rewardEnglish='Old reward';await wallet.sync(shops[1],shops[1].members[0]);assert.equal(calls.at(-1).body.secondaryFields[0].value,'Choose your reward');assert(calls.at(-1).body.backFields.some(f=>f.label==='REWARD OPTIONS'&&f.value.includes('Cake')));const catalogCalls=calls.length;await wallet.sync(shops[1],shops[1].members[0]);assert.equal(calls.length,catalogCalls,'unchanged reward options must not consume quota');
const originalArt=calls[2].body;shops[2].members[0].visits=3;shops[2].engagement={levels:{enabled:true,metric:'visits',window:0,tiers:[{id:'gold',name:'Gold',threshold:2,multiplier:1,benefit:'Priority booking'}]}};await wallet.sync(shops[2],shops[2].members[0]);const withLevel=calls.at(-1).body;assert(withLevel.backFields.some(f=>f.value==='Gold — Priority booking'));for(const name of ['backgroundURL','stripURL','logoURL','headerFields','secondaryFields','footerFields','primaryFields','barcodeValue'])assert.deepEqual(withLevel[name],originalArt[name],'tier does not alter the existing Wallet face: '+name);const levelCalls=calls.length;await wallet.sync(shops[2],shops[2].members[0]);assert.equal(calls.length,levelCalls,'unchanged level does not consume quota');assert(!JSON.stringify(withLevel).includes('PRIVATE'));
console.log('PASS: three designs render valid PNG under provider limits; customer privacy and account scope; concurrent issue deduplication; unchanged updates consume no calls; visit updates use PUT; paused cards suspend without destructive revocation; optional tiers only in back fields, unchanged modern/classic artwork and no duplicate tier updates.');
sql.close();
